export const Countries = [
    "Bangladesh",
    "Bhutan",
    "Maldives",
    "Nepal",
    "Sri Lanka",
    "United Arab Emirates",
    "Hong Kong",
    "Malaysia",
    "Singapore",
    "Thailand",
    "China",
    "Bahrain",
    "Jordan",
    "Kuwait",
    "Oman",
    "Pakistan",
    "Qatar",
    "Saudi Arabia",
    "Brunei",
    "Cambodia",
    "East Timor",
    "India",
    "Indonesia",
    "Japan",
    "Korea",
    "Lao People's Democratic Republic",
    "Macau",
    "Myanmar",
    "Philippines",
    "Taiwan",
    "Vietnam",
    "New Zealand",
    "Papua New Guinea",
    "Austria",
    "Belgium",
    "Czech Republic",
    "Denmark",
    "France",
    "Germany",
    "Hungary",
    "Ireland",
    "Italy",
    "Liechtenstein",
    "Luxembourg",
    "Monaco",
    "Netherlands",
    "Poland",
    "Portugal",
    "Romania",
    "Slovakia",
    "Spain",
    "Sweden",
    "Switzerland",
    "United Kingdom",
    "Vatican City State",
    "Andorra",
    "Belarus",
    "Bulgaria",
    "Canary Islands",
    "Cyprus",
    "Estonia",
    "Falkland Islands",
    "Faroe Islands",
    "Finland",
    "Gibraltar",
    "Greece",
    "Greenland",
    "Guernsey",
    "Iceland",
    "Israel",
    "Jersey",
    "Latvia",
    "Lithuania",
    "Malta",
    "Norway",
    "Slovenia",
    "Turkey",
    "American Samoa",
    "Canada",
    "Guam",
    "Marshall Islands",
    "Mexico",
    "Puerto Rico",
    "Saipan",
    "Virgin Islands (US)",
    "Anguilla",
    "Antigua",
    "Argentina",
    "Aruba",
    "Bahamas",
    "Barbados",
    "Belize",
    "Bermuda",
    "Bolivia",
    "Bonaire",
    "Brazil",
    "Cayman Islands",
    "Chile",
    "Colombia",
    "Costa Rica",
    "Cuba",
    "Curacao",
    "Dominica",
    "Dominican Republic",
    "Ecuador",
    "El Salvador",
    "French Guyana",
    "Grenada",
    "Guadeloupe",
    "Guatemala",
    "Guyana (British)",
    "Haiti",
    "Honduras",
    "Jamaica",
    "Martinique",
    "Montserrat",
    "Nevis",
    "Nicaragua",
    "Panama",
    "Paraguay",
    "Peru",
    "St. Barthelemy",
    "St. Eustatius",
    "St. Kitts",
    "St. Lucia",
    "St. Maarten",
    "St. Vincent",
    "Suriname",
    "Trinidad and Tobago",
    "Turks and Caicos Islands",
    "Uruguay",
    "Venezuela",
    "Virgin Islands (British)",
    "Afghanistan",
    "Albania",
    "Algeria",
    "Angola",
    "Armenia",
    "Azerbaijan",
    "Benin",
    "Bosnia and Herzegovina",
    "Botswana",
    "Burkina Faso",
    "Burundi",
    "Cameroon",
    "Cape Verde",
    "Central African Republic",
    "Chad",
    "Comoros",
    "Congo",
    "Congo, The Democratic Republic",
    "Cook Islands",
    "Cote d'Ivoire",
    "Croatia",
    "Djibouti",
    "Eritrea",
    "Ethiopia",
    "Fiji",
    "Gabon",
    "Gambia",
    "Georgia",
    "Guinea Republic",
    "Guinea-Bissau",
    "Guinea-Equatorial",
    "Iran",
    "Iraq",
    "Kazakhstan",
    "Kiribati",
    "Kosovo",
    "Kyrgyzstan",
    "Lebanon",
    "Lesotho",
    "Liberia",
    "Libya",
    "Macedonia",
    "Madagascar",
    "Malawi",
    "Mali",
    "Mauritania",
    "Mayotte",
    "Micronesia",
    "Moldova",
    "Mongolia",
    "Montenegro",
    "Morocco",
    "Namibia",
    "Nauru",
    "New Caledonia",
    "Niger",
    "Niue",
    "Palau",
    "Reunion",
    "Russian Federation",
    "Rwanda",
    "Saint Helena",
    "Samoa",
    "San Marino",
    "Sao Tome and Principe",
    "Senegal",
    "Serbia",
    "Seychelles",
    "Sierra Leone",
    "Solomon Islands",
    "Somalia",
    "Somaliland, Rep of (North Somalia)",
    "South Sudan",
    "Swaziland",
    "Syria",
    "Tahiti",
    "Tajikistan",
    "Togo",
    "Tonga",
    "Tunisia",
    "Turkmenistan",
    "Tuvalu",
    "Ukraine",
    "Uzbekistan",
    "Vanuatu",
    "Yemen",
    "Zambia",
    "United States Of America",
    "Egypt",
    "Ghana",
    "Kenya",
    "Mauritius",
    "Mozambique",
    "Nigeria",
    "South Africa",
    "Sudan",
    "Tanzania",
    "Uganda",
    "Zimbabwe",
    "Australia",
    "Rest Of The World"
]

export const countryCodeMap = {
  Afghanistan: { code: "AF", callingCode: "+93" },
  Albania: { code: "AL", callingCode: "+355" },
  Algeria: { code: "DZ", callingCode: "+213" },
  "American Samoa": { code: "AS", callingCode: "+1684" },
  Andorra: { code: "AD", callingCode: "+376" },
  Angola: { code: "AO", callingCode: "+244" },
  Anguilla: { code: "AI", callingCode: "+1264" },
  Antigua: { code: "AG", callingCode: "+1268" },
  Argentina: { code: "AR", callingCode: "+54" },
  Armenia: { code: "AM", callingCode: "+374" },
  Aruba: { code: "AW", callingCode: "+297" },
  Australia: { code: "AU", callingCode: "+61" },
  Austria: { code: "AT", callingCode: "+43" },
  Azerbaijan: { code: "AZ", callingCode: "+994" },
  Bahamas: { code: "BS", callingCode: "+1242" },
  Bahrain: { code: "BH", callingCode: "+973" },
  Bangladesh: { code: "BD", callingCode: "+880" },
  Barbados: { code: "BB", callingCode: "+1246" },
  Belarus: { code: "BY", callingCode: "+375" },
  Belgium: { code: "BE", callingCode: "+32" },
  Belize: { code: "BZ", callingCode: "+501" },
  Benin: { code: "BJ", callingCode: "+229" },
  Bermuda: { code: "BM", callingCode: "+1441" },
  Bhutan: { code: "BT", callingCode: "+975" },
  Bolivia: { code: "BO", callingCode: "+591" },
  Bonaire: { code: "BQ", callingCode: "+599" },
  "Bosnia and Herzegovina": { code: "BA", callingCode: "+387" },
  Botswana: { code: "BW", callingCode: "+267" },
  Brazil: { code: "BR", callingCode: "+55" },
  Brunei: { code: "BN", callingCode: "+673" },
  Bulgaria: { code: "BG", callingCode: "+359" },
  "Burkina Faso": { code: "BF", callingCode: "+226" },
  Burundi: { code: "BI", callingCode: "+257" },
  Cambodia: { code: "KH", callingCode: "+855" },
  Cameroon: { code: "CM", callingCode: "+237" },
  Canada: { code: "CA", callingCode: "+1" },
  "Canary Islands": { code: "IC", callingCode: "+34" },
  "Cape Verde": { code: "CV", callingCode: "+238" },
  "Cayman Islands": { code: "KY", callingCode: "+1345" },
  "Central African Republic": { code: "CF", callingCode: "+236" },
  Chad: { code: "TD", callingCode: "+235" },
  Chile: { code: "CL", callingCode: "+56" },
  China: { code: "CN", callingCode: "+86" },
  Colombia: { code: "CO", callingCode: "+57" },
  Comoros: { code: "KM", callingCode: "+269" },
  Congo: { code: "CG", callingCode: "+242" },
  "Congo, The Democratic Republic": { code: "CD", callingCode: "+243" },
  "Cook Islands": { code: "CK", callingCode: "+682" },
  "Costa Rica": { code: "CR", callingCode: "+506" },
  "Cote d'Ivoire": { code: "CI", callingCode: "+225" },
  Croatia: { code: "HR", callingCode: "+385" },
  Cuba: { code: "CU", callingCode: "+53" },
  Curacao: { code: "CW", callingCode: "+599" },
  Cyprus: { code: "CY", callingCode: "+357" },
  "Czech Republic": { code: "CZ", callingCode: "+420" },
  Denmark: { code: "DK", callingCode: "+45" },
  Djibouti: { code: "DJ", callingCode: "+253" },
  Dominica: { code: "DM", callingCode: "+1767" },
  "Dominican Republic": { code: "DO", callingCode: "+1809" },
  "East Timor": { code: "TL", callingCode: "+670" },
  Ecuador: { code: "EC", callingCode: "+593" },
  Egypt: { code: "EG", callingCode: "+20" },
  "El Salvador": { code: "SV", callingCode: "+503" },
  Eritrea: { code: "ER", callingCode: "+291" },
  Estonia: { code: "EE", callingCode: "+372" },
  Ethiopia: { code: "ET", callingCode: "+251" },
  "Falkland Islands": { code: "FK", callingCode: "+500" },
  "Faroe Islands": { code: "FO", callingCode: "+298" },
  Fiji: { code: "FJ", callingCode: "+679" },
  Finland: { code: "FI", callingCode: "+358" },
  France: { code: "FR", callingCode: "+33" },
  "French Guyana": { code: "GF", callingCode: "+594" },
  Gabon: { code: "GA", callingCode: "+241" },
  Gambia: { code: "GM", callingCode: "+220" },
  Georgia: { code: "GE", callingCode: "+995" },
  Germany: { code: "DE", callingCode: "+49" },
  Ghana: { code: "GH", callingCode: "+233" },
  Gibraltar: { code: "GI", callingCode: "+350" },
  Greece: { code: "GR", callingCode: "+30" },
  Greenland: { code: "GL", callingCode: "+299" },
  Grenada: { code: "GD", callingCode: "+1473" },
  Guadeloupe: { code: "GP", callingCode: "+590" },
  Guam: { code: "GU", callingCode: "+1671" },
  Guatemala: { code: "GT", callingCode: "+502" },
  Guernsey: { code: "GG", callingCode: "+44" },
  "Guinea Republic": { code: "GN", callingCode: "+224" },
  "Guinea-Bissau": { code: "GW", callingCode: "+245" },
  "Guinea-Equatorial": { code: "GQ", callingCode: "+240" },
  "Guyana (British)": { code: "GY", callingCode: "+592" },
  Haiti: { code: "HT", callingCode: "+509" },
  Honduras: { code: "HN", callingCode: "+504" },
  "Hong Kong": { code: "HK", callingCode: "+852" },
  Hungary: { code: "HU", callingCode: "+36" },
  Iceland: { code: "IS", callingCode: "+354" },
  India: { code: "IN", callingCode: "+91" },
  Indonesia: { code: "ID", callingCode: "+62" },
  Iran: { code: "IR", callingCode: "+98" },
  Iraq: { code: "IQ", callingCode: "+964" },
  Ireland: { code: "IE", callingCode: "+353" },
  Israel: { code: "IL", callingCode: "+972" },
  Italy: { code: "IT", callingCode: "+39" },
  Jamaica: { code: "JM", callingCode: "+1876" },
  Japan: { code: "JP", callingCode: "+81" },
  Jersey: { code: "JE", callingCode: "+44" },
  Jordan: { code: "JO", callingCode: "+962" },
  Kazakhstan: { code: "KZ", callingCode: "+7" },
  Kenya: { code: "KE", callingCode: "+254" },
  Kiribati: { code: "KI", callingCode: "+686" },
  Korea: { code: "KR", callingCode: "+82" },
  Kosovo: { code: "XK", callingCode: "+383" },
  Kuwait: { code: "KW", callingCode: "+965" },
  Kyrgyzstan: { code: "KG", callingCode: "+996" },
  "Lao People's Democratic Republic": { code: "LA", callingCode: "+856" },
  Latvia: { code: "LV", callingCode: "+371" },
  Lebanon: { code: "LB", callingCode: "+961" },
  Lesotho: { code: "LS", callingCode: "+266" },
  Liberia: { code: "LR", callingCode: "+231" },
  Libya: { code: "LY", callingCode: "+218" },
  Liechtenstein: { code: "LI", callingCode: "+423" },
  Lithuania: { code: "LT", callingCode: "+370" },
  Luxembourg: { code: "LU", callingCode: "+352" },
  Macau: { code: "MO", callingCode: "+853" },
  Macedonia: { code: "MK", callingCode: "+389" },
  Madagascar: { code: "MG", callingCode: "+261" },
  Malawi: { code: "MW", callingCode: "+265" },
  Malaysia: { code: "MY", callingCode: "+60" },
  Maldives: { code: "MV", callingCode: "+960" },
  Mali: { code: "ML", callingCode: "+223" },
  Malta: { code: "MT", callingCode: "+356" },
  "Marshall Islands": { code: "MH", callingCode: "+692" },
  Martinique: { code: "MQ", callingCode: "+596" },
  Mauritania: { code: "MR", callingCode: "+222" },
  Mauritius: { code: "MU", callingCode: "+230" },
  Mayotte: { code: "YT", callingCode: "+262" },
  Mexico: { code: "MX", callingCode: "+52" },
  Micronesia: { code: "FM", callingCode: "+691" },
  Moldova: { code: "MD", callingCode: "+373" },
  Monaco: { code: "MC", callingCode: "+377" },
  Mongolia: { code: "MN", callingCode: "+976" },
  Montenegro: { code: "ME", callingCode: "+382" },
  Montserrat: { code: "MS", callingCode: "+1664" },
  Morocco: { code: "MA", callingCode: "+212" },
  Mozambique: { code: "MZ", callingCode: "+258" },
  Myanmar: { code: "MM", callingCode: "+95" },
  Namibia: { code: "NA", callingCode: "+264" },
  Nauru: { code: "NR", callingCode: "+674" },
  Nepal: { code: "NP", callingCode: "+977" },
  Netherlands: { code: "NL", callingCode: "+31" },
  Nevis: { code: "KN", callingCode: "+1869" },
  "New Caledonia": { code: "NC", callingCode: "+687" },
  "New Zealand": { code: "NZ", callingCode: "+64" },
  Nicaragua: { code: "NI", callingCode: "+505" },
  Niger: { code: "NE", callingCode: "+227" },
  Nigeria: { code: "NG", callingCode: "+234" },
  Niue: { code: "NU", callingCode: "+683" },
  Norway: { code: "NO", callingCode: "+47" },
  Oman: { code: "OM", callingCode: "+968" },
  Pakistan: { code: "PK", callingCode: "+92" },
  Palau: { code: "PW", callingCode: "+680" },
  Panama: { code: "PA", callingCode: "+507" },
  "Papua New Guinea": { code: "PG", callingCode: "+675" },
  Paraguay: { code: "PY", callingCode: "+595" },
  Peru: { code: "PE", callingCode: "+51" },
  Philippines: { code: "PH", callingCode: "+63" },
  Poland: { code: "PL", callingCode: "+48" },
  Portugal: { code: "PT", callingCode: "+351" },
  "Puerto Rico": { code: "PR", callingCode: "+1787" },
  Qatar: { code: "QA", callingCode: "+974" },
  "Rest Of The World": { code: "XX", callingCode: "+000" },
  Reunion: { code: "RE", callingCode: "+262" },
  Romania: { code: "RO", callingCode: "+40" },
  "Russian Federation": { code: "RU", callingCode: "+7" },
  Rwanda: { code: "RW", callingCode: "+250" },
  Saipan: { code: "MP", callingCode: "+1670" },
  "Saint Helena": { code: "SH", callingCode: "+290" },
  Samoa: { code: "WS", callingCode: "+685" },
  "San Marino": { code: "SM", callingCode: "+378" },
  "Sao Tome and Principe": { code: "ST", callingCode: "+239" },
  "Saudi Arabia": { code: "SA", callingCode: "+966" },
  Senegal: { code: "SN", callingCode: "+221" },
  Serbia: { code: "RS", callingCode: "+381" },
  Seychelles: { code: "SC", callingCode: "+248" },
  "Sierra Leone": { code: "SL", callingCode: "+232" },
  Singapore: { code: "SG", callingCode: "+65" },
  Slovakia: { code: "SK", callingCode: "+421" },
  Slovenia: { code: "SI", callingCode: "+386" },
  "Solomon Islands": { code: "SB", callingCode: "+677" },
  Somalia: { code: "SO", callingCode: "+252" },
  "Somaliland, Rep of (North Somalia)": { code: "SO", callingCode: "+252" },
  "South Africa": { code: "ZA", callingCode: "+27" },
  "South Sudan": { code: "SS", callingCode: "+211" },
  Spain: { code: "ES", callingCode: "+34" },
  "Sri Lanka": { code: "LK", callingCode: "+94" },
  "St. Barthelemy": { code: "BL", callingCode: "+590" },
  "St. Eustatius": { code: "BQ", callingCode: "+599" },
  "St. Kitts": { code: "KN", callingCode: "+1869" },
  "St. Lucia": { code: "LC", callingCode: "+1758" },
  "St. Maarten": { code: "SX", callingCode: "+1721" },
  "St. Vincent": { code: "VC", callingCode: "+1784" },
  Sudan: { code: "SD", callingCode: "+249" },
  Suriname: { code: "SR", callingCode: "+597" },
  Swaziland: { code: "SZ", callingCode: "+268" },
  Sweden: { code: "SE", callingCode: "+46" },
  Switzerland: { code: "CH", callingCode: "+41" },
  Syria: { code: "SY", callingCode: "+963" },
  Tahiti: { code: "PF", callingCode: "+689" },
  Taiwan: { code: "TW", callingCode: "+886" },
  Tajikistan: { code: "TJ", callingCode: "+992" },
  Tanzania: { code: "TZ", callingCode: "+255" },
  Thailand: { code: "TH", callingCode: "+66" },
  Togo: { code: "TG", callingCode: "+228" },
  Tonga: { code: "TO", callingCode: "+676" },
  "Trinidad and Tobago": { code: "TT", callingCode: "+1868" },
  Tunisia: { code: "TN", callingCode: "+216" },
  Turkey: { code: "TR", callingCode: "+90" },
  Turkmenistan: { code: "TM", callingCode: "+993" },
  "Turks and Caicos Islands": { code: "TC", callingCode: "+1649" },
  Tuvalu: { code: "TV", callingCode: "+688" },
  Uganda: { code: "UG", callingCode: "+256" },
  Ukraine: { code: "UA", callingCode: "+380" },
  "United Arab Emirates": { code: "AE", callingCode: "+971" },
  "United Kingdom": { code: "GB", callingCode: "+44" },
  "United States Of America": { code: "US", callingCode: "+1" },
  Uruguay: { code: "UY", callingCode: "+598" },
  Uzbekistan: { code: "UZ", callingCode: "+998" },
  Vanuatu: { code: "VU", callingCode: "+678" },
  "Vatican City State": { code: "VA", callingCode: "+39" },
  Venezuela: { code: "VE", callingCode: "+58" },
  Vietnam: { code: "VN", callingCode: "+84" },
  "Virgin Islands (British)": { code: "VG", callingCode: "+1284" },
  "Virgin Islands (US)": { code: "VI", callingCode: "+1340" },
  Yemen: { code: "YE", callingCode: "+967" },
  Zambia: { code: "ZM", callingCode: "+260" },
  Zimbabwe: { code: "ZW", callingCode: "+263" },
}