export const Countries = [
    "Bangladesh",
    "Bhutan",
    "Maldives",
    "Nepal",
    "Sri Lanka",
    "United Arab Emirates",
    "Hong Kong",
    "Malaysia",
    "Singapore",
    "Thailand",
    "China",
    "Bahrain",
    "Jordan",
    "Kuwait",
    "Oman",
    "Pakistan",
    "Qatar",
    "Saudi Arabia",
    "Brunei",
    "Cambodia",
    "East Timor",
    "Indonesia",
    "Japan",
    "Korea",
    "Lao People's Democratic Republic",
    "Macau",
    "Myanmar",
    "Philippines",
    "Taiwan",
    "Vietnam",
    "New Zealand",
    "Papua New Guinea",
    "Austria",
    "Belgium",
    "Czech Republic",
    "Denmark",
    "France",
    "Germany",
    "Hungary",
    "Ireland",
    "Italy",
    "Liechtenstein",
    "Luxembourg",
    "Monaco",
    "Netherlands",
    "Poland",
    "Portugal",
    "Romania",
    "Slovakia",
    "Spain",
    "Sweden",
    "Switzerland",
    "United Kingdom",
    "Vatican City State",
    "Andorra",
    "Belarus",
    "Bulgaria",
    "Canary Islands",
    "Cyprus",
    "Estonia",
    "Falkland Islands",
    "Faroe Islands",
    "Finland",
    "Gibraltar",
    "Greece",
    "Greenland",
    "Guernsey",
    "Iceland",
    "Israel",
    "Jersey",
    "Latvia",
    "Lithuania",
    "Malta",
    "Norway",
    "Slovenia",
    "Turkey",
    "American Samoa",
    "Canada",
    "Guam",
    "Marshall Islands",
    "Mexico",
    "Puerto Rico",
    "Saipan",
    "Virgin Islands (US)",
    "Anguilla",
    "Antigua",
    "Argentina",
    "Aruba",
    "Bahamas",
    "Barbados",
    "Belize",
    "Bermuda",
    "Bolivia",
    "Bonaire",
    "Brazil",
    "Cayman Islands",
    "Chile",
    "Colombia",
    "Costa Rica",
    "Cuba",
    "Curacao",
    "Dominica",
    "Dominican Republic",
    "Ecuador",
    "El Salvador",
    "French Guyana",
    "Grenada",
    "Guadeloupe",
    "Guatemala",
    "Guyana (British)",
    "Haiti",
    "Honduras",
    "Jamaica",
    "Martinique",
    "Montserrat",
    "Nevis",
    "Nicaragua",
    "Panama",
    "Paraguay",
    "Peru",
    "St. Barthelemy",
    "St. Eustatius",
    "St. Kitts",
    "St. Lucia",
    "St. Maarten",
    "St. Vincent",
    "Suriname",
    "Trinidad and Tobago",
    "Turks and Caicos Islands",
    "Uruguay",
    "Venezuela",
    "Virgin Islands (British)",
    "Afghanistan",
    "Albania",
    "Algeria",
    "Angola",
    "Armenia",
    "Azerbaijan",
    "Benin",
    "Bosnia and Herzegovina",
    "Botswana",
    "Burkina Faso",
    "Burundi",
    "Cameroon",
    "Cape Verde",
    "Central African Republic",
    "Chad",
    "Comoros",
    "Congo",
    "Congo, The Democratic Republic",
    "Cook Islands",
    "Cote d'Ivoire",
    "Croatia",
    "Djibouti",
    "Eritrea",
    "Ethiopia",
    "Fiji",
    "Gabon",
    "Gambia",
    "Georgia",
    "Guinea Republic",
    "Guinea-Bissau",
    "Guinea-Equatorial",
    "Iran",
    "Iraq",
    "Kazakhstan",
    "Kiribati",
    "Korea",
    "Kosovo",
    "Kyrgyzstan",
    "Lebanon",
    "Lesotho",
    "Liberia",
    "Libya",
    "Macedonia",
    "Madagascar",
    "Malawi",
    "Mali",
    "Mauritania",
    "Mayotte",
    "Micronesia",
    "Moldova",
    "Mongolia",
    "Montenegro",
    "Morocco",
    "Namibia",
    "Nauru",
    "New Caledonia",
    "Niger",
    "Niue",
    "Palau",
    "Reunion",
    "Russian Federation",
    "Rwanda",
    "Saint Helena",
    "Samoa",
    "San Marino",
    "Sao Tome and Principe",
    "Senegal",
    "Serbia",
    "Seychelles",
    "Sierra Leone",
    "Solomon Islands",
    "Somalia",
    "Somaliland, Rep of (North Somalia)",
    "South Sudan",
    "Swaziland",
    "Syria",
    "Tahiti",
    "Tajikistan",
    "Togo",
    "Tonga",
    "Tunisia",
    "Turkmenistan",
    "Tuvalu",
    "Ukraine",
    "Uzbekistan",
    "Vanuatu",
    "Yemen",
    "Zambia",
    "United States Of America",
    "Egypt",
    "Ghana",
    "Kenya",
    "Mauritius",
    "Mozambique",
    "Nigeria",
    "South Africa",
    "Sudan",
    "Tanzania",
    "Uganda",
    "Zimbabwe",
    "Australia",
    "Rest Of The World"
]