"use client";

import Footer from "@/app/_components/Footer";
import FrontHeader from "@/app/_components/FrontHeader";

export default function MerchantAgreementPage() {
  return (
    <>
    <FrontHeader />
    <main className="bg-[#f8f9ff] min-h-screen py-12 px-4">
      <div className="max-w-4xl mx-auto bg-white rounded-2xl shadow-lg p-6 md:p-12">
        <h1 className="text-3xl md:text-4xl font-extrabold text-[#232C65] mb-2">
          Merchant Agreement
        </h1>
        <div className="w-32 h-2 bg-yellow-400 rounded mb-6" />
        <p className="text-gray-600 mb-8">Version 1.0</p>

        <section className="space-y-8 text-gray-800 text-justify">
          <div>
            <p className="mb-4">
              This Merchant Agreement (“Agreement”) is between you (company/individual/firm/partnership/body corporate), together with any company or other business entity you are representing, if any (hereinafter collectively referred as “Merchant” or “you” or “User”); and <strong>SunEx Services Private Limited</strong>, a company incorporated under the laws of India, having its registered office at 901, 9th Floor, Emerald 2 CHS LTD, Royal Palms, Aarey Milk Colony, Goregaon East, Mumbai 400 065, offering ‘Logistics Management Services’, under the name ‘SunEx Services’ (hereinafter referred to as “we” or “SunEx” or “Company”, and together with the User referred jointly as the “Parties” and individually as a “Party”).
            </p>
          </div>

          <div>
            <h2 className="text-xl font-bold text-[#2563eb] mb-2">BACKGROUND</h2>
            <p className="mb-4">
              This Agreement comes into effect when you register to use the Services (as defined below), or click on “Continue” box, and accept the terms and conditions provided herein.
            </p>
            <p className="mb-4">
              By registering or clicking on the ‘Continue’ box, you signify your absolute, irrevocable and unconditional consent to all the provisions of this Agreement in its entirety. This Agreement constitutes a legally binding agreement between you and SunEx Services. This Agreement is an extension of the terms and conditions (Annexure 1) and privacy policy (Annexure 2), under which you’re allowed to use SunEx’s website (“Website”) and application (“App”), and how SunEx will treat your account while you are a member. If you have any questions about our terms, feel free to contact us at <a href="mailto:support@sunexservices.com" className="text-blue-600 underline">support@sunexservices.com</a>.
            </p>
            <p className="mb-4">
              You are advised to read this Agreement carefully. You expressly represent and warrant that you will not avail the Services if you do not understand, agree to become a party to, and abide by all of the terms and conditions specified below. Any violation of this Agreement may result in legal liability upon you.
            </p>
            <p className="mb-4">
              The Website/App and the online/offline services of SunEx or its affiliates, provides access to a platform that facilitates more comfortable form of e-commerce where you can use the logistics services according to your requirements as designated by SunEx from time to time (“Service(s)”).
            </p>
            <p className="mb-4">
              This Agreement, among other things, provides the terms and conditions for use of the Services, primarily through a web-based practice management software hosted and managed remotely through the Website/App.
            </p>
            <p className="mb-4">
              This Agreement is an electronic record in terms of Information Technology Act, 2000 and generated by a computer system, and does not require any physical or digital signatures. This Agreement is published in accordance with the provisions of Rule 3(1) of the Information Technology (Intermediaries guidelines) Rules, 2011 that require publishing of the rules and regulations, privacy policy and terms of usage for access or usage of the website/service.
            </p>
            <p className="mb-4">
              SunEx reserves the right to modify the terms of this Agreement, at any time, without giving you any prior notice. Your use of the Service following any such modification constitutes your agreement to follow and be bound by the terms of the Agreement, as modified.
            </p>
            <p className="mb-4">
              Any additional terms and conditions, standard operating procedures (SOPs), service-level agreements (SLAs), terms of use, disclaimers and other policies applicable to general and specific areas of this Agreement, Website, App and/or Service shall be construed to form an integral part of this Agreement and any breach thereof will be construed as a breach of this Agreement.
            </p>
            <p className="mb-4">
              Your access to use the Services will be solely at the discretion of SunEx.
            </p>
          </div>

          <div>
            <h2 className="text-xl font-bold text-[#2563eb] mb-2">Definitions</h2>
            <p className="mb-4">
              All capitalized terms used in this Merchant Agreement shall have the meanings ascribed to them in the Terms &amp; Conditions available here, and privacy policy available here, unless the context otherwise provides or requires.
            </p>
          </div>

          <div>
            <h2 className="text-xl font-bold text-[#2563eb] mb-2">Methodology for Pricing</h2>
            <p className="mb-4">
              With respect to Shipments, we have specific weight and size limitations for each individual Shipment which may vary basis the Shipping Vendor and/or location to which the Shipment is being shipped, although there is no restriction to the total weight of all Your Shipments collectively or on the number of boxes in each of Your Shipment.
            </p>
            <p className="mb-4">
              Volumetric weight of a Shipment will be system calculated at the time of booking in the panel of the Platforms. The formula used to calculate the volumetric weight is: length(cm) x breadth(cm) x height(cm) divided by 5000.
            </p>
            <p className="mb-4">
              <strong>For example:</strong> If a shipment has the following dimensions: Length 30cm, Breadth 25cm, Height 40cm, the volumetric weight will be – 30 x 25 x 40 / 5000 = 6 KGs
            </p>
            <p className="mb-4">
              For all shipments, billing will be based on the following criteria –
            </p>
            <ul className="list-disc pl-6">
                <li>For shipments with a volumetric weight up to 5kg, charges will be applied on the basis of dead weight.</li>
                <li>For shipments exceeding 5kg volumetric weight, billing will be done based on whichever is higher between dead weight and volumetric weight.</li>
              </ul>
            <p className="mb-4">
              Additionally, certain goods that require specialized handling, as defined under our internal operational guidelines, will be subject to an applicable special handling fee.
            </p>
          </div>

          <div>
            <h2 className="text-xl font-bold text-[#2563eb] mb-2">Customer Journey After Booking of Shipment on the Platforms</h2>
            <p className="mb-4">
              Depending upon the pick-up location, you will be shown two options at the time of booking Shipments, either SunEx-Pickup or Self-Ship. Under SunEx-Pickup, we come and collect the Shipments from Your doorstep (i.e. from the location provided by You), or alternatively You can select Self-Ship wherein, You are required to drop off the Shipments to Our nearest hub.
            </p>
            <p className="mb-4">
              Once Your Shipment reaches Our hub, it is scanned, weighed and sorted as per the destination location and service selected. In case, there is any weight discrepancy in the weight mentioned and the weight recorded, it is put on hold and an email notification is sent to You for approval. Once approved it is connected to its destination. Once the package leaves Our hub, there is no additional weight discrepancy that will be debited to Your account later.
            </p>
            <p className="mb-4">
              In case of international shipments, upon Shipments reaching the destination country after clearing the customs in India, the Shipments are custom cleared in the destination country and the Shipments are received at our local office from where it is forwarded to the last mile shipping carrier. Our final mile delivery Shipping Vendors vary from country to country like in the USA our Shipping Vendors are UPS, USPS and Fedex, and in Europe our Shipping Vendors are DPD or postal networks and in Canada our Shipping Vendors are Canada Post and UPS. It be noted that Our Shipping Vendors may change from time to time. In case of branded networks like DHL, UPS, FedEx &amp; Aramex, the Shipments are connected to their respective hubs in Mumbai itself and the entire journey of the Shipment is available on their tracking numbers on their respective websites.
            </p>
            <p className="mb-4">
              <strong>Delivery Attempt(s) &amp; RTOs:</strong> All Shipments are attempted to be delivered at least once, in many cases deliveries are attempted twice depending upon the last mile Shipping Vendor’s policy. In case no one is available to receive the packages, the Shipments maybe:
            </p>
            <ul className="list-disc pl-6">
                <li>Dropped with the neighbour;</li>
                <li>Dropped to the local post office for pickup by the Customer;</li>
                <li>Dropped in a secure location outside the house or mailbox of the Customer.</li>
              </ul>
            <p className="mb-4">
              <strong>RTO under SunEx Direct Service:</strong> If any Shipment is undeliverable due to the below mentioned reasons, the shipment will be forwarded back to Our or Our partner’s local office in the destination country. The RTO charges will be billed to Your account and the package will be destroyed in most cases, except USA and Europe. Re-forwarding option is available for USA, Europe and the charges for the same will be extra.
            </p>
            <p className="mb-4">
              <strong>RTO under branded networks – DHL, FedEx, UPS &amp; Aramex:</strong> If any Shipment is undeliverable due to the below mentioned reasons it will be forwarded back to You in India, in case it is not destroyed by the Shipping Vendor (depending upon the internal policy of the respective Shipping Vendor) in the destination country – and the applicable RTO charges will be billed to Your account. Also, if the RTO is due to non-payment of any duties and taxes by the Customer – it will be returned and billed to Your account.
            </p>
            <p className="mb-4">
              <strong>Reasons for Shipment being Undeliverable:</strong>
            </p>
                          <ul className="list-disc pl-6">
                <li>Incorrect address mentioned at the time of booking and/or on the Shipment;</li>
                <li>Missing/incomplete information like apt number, street name etc.</li>
                <li>Customer refused to accept the Shipment at the time of delivery</li>
                <li>Customer refused to pay the taxes and/or duties.</li>
              </ul>
            <p className="mb-4">
              SunEx reserves the right to return to the User, the Shipments which are not accepted by the Customer for any reason whatsoever, and to apply the RTO (return to origin) charges as per the prevailing rate.
            </p>
            <p className="mb-4">
              In case of non-acceptance of the RTO Shipment by the User or in case the User is not reachable for RTO Shipment, SunEx reserves the right to levy suitable demurrage/incidental charges for extended storage of such products for any period exceeding 7 (seven) days from initiation of the returns and up to 45 (forty-five) days from such date. In case of non-acceptance of the Shipment beyond 10 (ten) days from the first RTO undelivered date/first RTO delivery attempt date, SunEx has the right to dispose such products and the User will forfeit all claims in this regard towards SunEx. Also, User will be required to pay charges for disposing the Shipment, along with all other charges (including demurrage/incidental charges).
            </p>
          </div>

          <div>
            <h2 className="text-xl font-bold text-[#2563eb] mb-2">SunEx’s Refund and Liability Policy</h2>
            <p className="mb-4">
              <strong>Claims Maintainable:</strong> Our goal is to fulfil all Your Shipments securely however if anything goes wrong, we’ve got you covered! You may be entitled to file a claim and get compensation in the following circumstances:
            </p>
            <ul className="list-disc pl-6">
              <li>
                <strong>Case 1:</strong> No first scan by the last mile carrier in the destination country (i.e. for example You booked a shipment via SunEx Direct service to the USA, and the last mile Shipping Vendor like UPS was generated but no scan is showing there.)
                <ul className="list-disc pl-6">
                  <li>In case of 0-100g shipments, the claim amount will be 30% (thirty percent) of invoice value plus shipping charges, with a maximum capping of Rs.1,000/- (Indian Rupees One Thousand Only) inclusive of the shipping charges paid/payable by You.</li>
                  <li>For all shipments above 100g, the claim amount will be 30% (thirty percent) of the invoice plus shipping charges, with a maximum amount of Rs.4,000/- (Indian Rupees Four Thousand Only) inclusive of the shipping charges paid/payable by You.</li>
                </ul>
              </li>
              <li>
                <strong>Case 2:</strong> No delivery scan by the last mile Shipping Vendor or the Shipment is Lost in transit.
                <br />
                This is a rare case wherein the Shipment has been delivered by the last mile Shipping Vendor but the scanning does not show the final delivery scan – as it is handled by the postal service of the destination country. In case your customer claims for non-delivery and a refund have been made from your side to the customer You may claim for a refund. Claim will be processed as per Claim Policy mentioned below upon presentation of buyer-seller chat along with proof of refund. In case of branded networks like DHL, UPS and Fedex, the claim policy will remain the same but the timeline to process the claim will be as per the respective carrier’s policy.
                <br />
                To file a claim, please share the SunEx AWB along with the relevant documents at <a href="mailto:sunexservicespl@gmail.com" className="text-blue-600 underline">sunexservicespl@gmail.com</a>
              </li>
              <li>
                <strong>Case 3:</strong> Package lost before inwarding in Mumbai Hub
                <br />
                If pickup is done by SunEx’s team refund will be as per policy (mentioned below) in case of 3PL (third party logistics) only the shipping charges will be refunded.
              </li>
            </ul>
            <p className="mb-4">
              <strong>No Claims Maintainable:</strong> You will be entitled to claims only in the specific circumstance mentioned above, and SunEx shall not be liable to entertain any claims in any other circumstances including the below:
            </p>
            <ul className="list-disc pl-6">
              <li>non-delivery occurs on account of a mistake by you (i.e. wrong name or address or any other wrong information). In such a situation, reconnection of Shipment, if possible, shall be intimated to You by SunEx with applicable extra cost that shall be incurred for reconnection. However, You hereby agree and acknowledge that reconnection of shipment is not guaranteed, which SunEx may undertake at its sole discretion ;</li>
              <li>if Shipment is detained by customs or similar authority;</li>
              <li>if a delivery attempt has been made but delivery has not been able to be completed for any reasons whatsoever;</li>
              <li>if the Shipment is damaged/ leaking/tampered with /or pilfered with on account of poor packaging of the Shipment(s);</li>
              <li>if Shipping Vendor does not provide for refund in the given circumstance;</li>
              <li>if Shipping Vendor claims the Shipment is delivered then it will be considered delivered and no refund claims to be entertained;</li>
            </ul>
            <p className="mb-4">
              <strong>Process and Terms To Make Claim:</strong> Notwithstanding anything contained herein or elsewhere, the claim policy shall be only applicable for SunEx Self-Services (i.e. SunEx Super Saver, SunEx Direct, SunEx Economy, SunEx First Class, SunEx Express, SunEx Premium, SunEx Premium UPS Ground, SunEx eCommerce DHL and SunEx CA Special), and for branded networks like DHL, FedEx, Aramex and UPS their respective refund/return policy shall apply. The following process/points need to be followed/complied with respect any claim(s):
            </p>
            <ul className="list-disc pl-6">
              <li>If You have any claim, you are requested to send your claim to <a href="mailto:sunexservicespl@gmail.com" className="text-blue-600 underline">sunexservicespl@gmail.com</a> with all supporting documents.</li>
              <li>After receiving your claim request SunEx’s support team will investigate the issue and contact the local office/Shipping Vendor to search for the Shipment and access the Claim.</li>
              <li>Upon completion of investigation SunEx will communicate the result to You or seek further information from you if required;</li>
              <li>SunEx endeavours to close each claim for refund within a period of 15 (fifteen) days from receiving a complaint from You. Please note while it is SunEx’s endeavour to close each refund case at the earliest, in certain cases it may require assistance of Shipping Vendors, which may require additional time.</li>
              <li>In the case You have availed of SunEx Direct services, and the Shipment has not been delivered within 30 (thirty) day of pick-up of the Shipment, You shall be entitled to refund in terms of this Merchant Agreement, provided there is no dispute. In case of dispute, time will be calculated 1 day after the dispute is resolved. In any cases other than SunEx Direct services or in case any additional docs are required the 30 (thirty) days refund policy will not be applicable.</li>
              <li>For any claim to be valid, the following points need to be observed by You to the extent applicable:
                <ul className="list-disc pl-6">
                  <li>claims shall be made at the earliest, however no claims shall be considered by SunEx if a period of 60 (sixty) days has lapsed from the date of the inward scan;</li>
                  <li>if any information is passed to You regarding the Shipment being stuck or undelivered or for RTO, and You don’t revert within a period of 7 (seven) days of the date of the said communication, then the Claim shall not be considered by SunEx;</li>
                  <li>if the Shipment in question shows scan status of ‘out for delivery’ or ‘awaiting delivery’, then no claim shall be entertained unless the chat record/screenshot with Customer is provided;</li>
                  <li>for any claims by You regarding non-connectivity of the Shipment(s) (i.e. where the User is claiming that the Shipment(s) have been picked up but not connected forward or scanned at the hub) – the signed copy of the manifest sheet of the pick-up against the disputed Shipment(s) have to be submitted along with the claim request by the User within 3 (three) days from the pickup date. Without the signed manifest no claim shall be maintainable;</li>
                  <li>in case of a damaged/pilfered/tampered/pressed/leaked Shipment(s), Customer shall mention negative remarks on POD (proof of delivery) copy to get claim for the Shipment. In the absence of any negative remarks on POD copy clearly stating such damage/pilferage/tampering/pressing/leakage, no claim shall be maintainable; and</li>
                  <li>Claims for any kind of damage/pilferage/tampering/leakage of the Shipment shall be entertained by SunEx only if made within a period of 48 (forty-eight) hours from the receipt/delivery of the Shipment and if the outer packaging done by SunEx or Shipping Vendor is damaged/altered/tampered. However, if the outer packaging done by the SunEx or Shipping Vendor is intact and not tampered with, in such a case, no claim(s) for any damage/pilferage/tampering/leakage shall be entertained by SunEx.</li>
                </ul>
              </li>
            </ul>
          </div>

          <div>
            <h2 className="text-xl font-bold text-[#2563eb] mb-2">Handling Charges, Remote Area Charges, Reforwarding Charges and other Charges</h2>
            <p className="mb-4">
              <strong>Shipping Charges:</strong> Shipping charges in case of SunEx branded services shall be decided on case to case basis.
            </p>
            <p className="mb-4">
              If Shipment is customs detained – additional charges will be applicable as per actual
            </p>
            <p className="mb-4">
              Please note that handing charges set out above are for a maximum Shipment weight of:
            </p>
            <ul className="list-disc pl-6">
                <li>In case of USA: 22 KGs (volume or dead weight whichever is higher)</li>
                <li>In case of UK: 30 KGs (volume or dead weight whichever is higher)</li>
                <li>In case of Europe: 30KGs (volume or dead weight whichever is higher)</li>
                <li>In case of Australia/NZ: 20 KGs (volume or dead weight whichever is higher)</li>
                <li>In case of Canada: 20 KGs (volume or dead weight whichever is higher)</li>
              </ul>
            <p className="mb-4">
              In case of package volume or dead weight is higher than above mentioned slabs there will be an additional handling charge of Rs 4000/- plus GST, up to a maximum of additional 10 KGs higher.
            </p>
            <p className="mb-4">
              <strong>Remote Area Charges:</strong> The said charges will be mentioned at the time of booking in case of SunEx branded services, for all other non-SunEx branded services remote area charges shall be applicable as per the respective service provider’s policy.
            </p>
            <p className="mb-4">
              <strong>Reforwarding Charges:</strong> The Reforwarding charges shall be as set below for SunEx branded services, or as amended from time to time, and for all other non-SunEx branded services reforwarding charges shall be applicable as per the respective service provider’s policy:
            </p>
            <ul className="list-disc pl-6">
                <li>USA: $15 for up to 500 grams, and $25 for 500 grams to up to 5 KG</li>
                <li>Europe: Euro 20 for up to 500 grams, and Euro 30 for 500 grams to up to 5 KG</li>
                <li>Canada: CAD 20 up to 500 grams, 500 grams to 5 KG CAD 30</li>
              </ul>
            <p className="mb-4">
              Additionally, certain goods that require specialized handling, as defined under our internal operational guidelines, will be subject to an applicable special handling fee.
            </p>
          </div>
        </section>
      </div>
    </main>
    <Footer />
    </>
  );
}